// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskDashboard.Api.Infrastructure.Data;

#nullable disable

namespace TaskDashboard.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323221715_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TaskDashboard.Api.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Education",
                            Description = "Group coursework and personal progress tracking.",
                            Name = "School MIS321"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Personal",
                            Description = "Small ongoing tasks to keep life running smoothly.",
                            Name = "Personal Admin"
                        });
                });

            modelBuilder.Entity("TaskDashboard.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Outline goals, milestones, and dashboard structure.",
                            DueDate = new DateTime(2026, 3, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 1,
                            ProjectId = 1,
                            Status = 0,
                            Title = "Draft project plan"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Implement DbContext, migrations, and basic endpoints.",
                            DueDate = new DateTime(2026, 3, 26, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = 2,
                            ProjectId = 1,
                            Status = 1,
                            Title = "Complete API scaffolding"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 23, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Use dashboard to manage personal recurring tasks.",
                            Priority = 0,
                            ProjectId = 2,
                            Status = 0,
                            Title = "Set up weekly review"
                        });
                });

            modelBuilder.Entity("TaskDashboard.Api.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskDashboard.Api.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskDashboard.Api.Domain.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
